config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get  'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  resources :sessions, only: %i[index show destroy]
  resource  :password, only: %i[edit update]
  namespace :identity do
    resource :email,              only: %i[edit update]
    resource :email_verification, only: %i[show create]
    resource :password_reset,     only: %i[new edit create update]
  end
  root 'home#index'
  resources :users, only: %i[index edit update] do
    member do
      delete :remove_attachment
      get :download
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :session
  attribute :user_agent, :ip_address

  delegate :user, to: :session, allow_nil: true
end

app/models/email_verification_token.rb
# frozen_string_literal: true

class EmailVerificationToken < ApplicationRecord
  belongs_to :user
end

app/models/password_reset_token.rb
# frozen_string_literal: true

class PasswordResetToken < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
# frozen_string_literal: true

class Session < ApplicationRecord
  belongs_to :user

  before_create do
    self.user_agent = Current.user_agent
    self.ip_address = Current.ip_address
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :email_verification_tokens, dependent: :destroy
  has_many :password_reset_tokens, dependent: :destroy
  has_many :sessions, dependent: :destroy
  has_many_attached :files

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, allow_nil: true, length: { minimum: 12 }

  before_validation if: -> { email.present? } do
    self.email = email.downcase.strip
  end

  before_validation if: :email_changed?, on: :update do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).delete_all
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_current_request_details
  before_action :authenticate

  private

  def authenticate
    if (session_record = Session.find_by_id(cookies.signed[:session_token]))
      Current.session = session_record
    else
      redirect_to sign_in_path
    end
  end

  def set_current_request_details
    Current.user_agent = request.user_agent
    Current.ip_address = request.ip
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < ApplicationController
  before_action :set_user

  def edit; end

  def update
    if !@user.authenticate(params[:current_password])
      redirect_to edit_password_path, alert: 'The current password you entered is incorrect'
    elsif @user.update(user_params)
      redirect_to root_path, notice: 'Your password has been changed'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = Current.user
  end

  def user_params
    params.permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  skip_before_action :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session_record = @user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: session_record.id, httponly: true }

      send_email_verification
      redirect_to root_path, notice: 'Welcome! You have signed up successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.permit(:email, :password, :password_confirmation)
  end

  def send_email_verification
    UserMailer.with(user: @user).email_verification.deliver_later
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate, only: %i[new create]

  before_action :set_session, only: :destroy

  def index
    @sessions = Current.user.sessions.order(created_at: :desc)
  end

  def new; end

  def create # rubocop:disable Metrics/AbcSize
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      @session = user.sessions.create!
      cookies.signed.permanent[:session_token] = { value: @session.id, httponly: true }

      redirect_to root_path, notice: 'Signed in successfully'
    else
      redirect_to sign_in_path(email_hint: params[:email]), alert: 'That email or password is incorrect'
    end
  end

  def destroy
    @session.destroy
    redirect_to(sessions_path, notice: 'That session has been logged out')
  end

  private

  def set_session
    @session = Current.user.sessions.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def index
    @current_user = Current.user
    @users = User.all
    @attachments = ActiveStorage::Attachment.where(record: User.all)
    @attachments = search(@attachments) if params[:commit]
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User was updated successfully.'
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def remove_attachment
    @file = ActiveStorage::Attachment.find(params[:id])
    @file.purge_later
    redirect_back fallback_location: users_path
  end

  def download
    @attachments = ActiveStorage::Attachment.where(record: User.all)
    @attachments = search(@attachments) if params[:created_from].present? || params[:created_to].present?
    pdf = AttachmentPdf.new(@attachments)
    send_data(pdf.render,
              filename: 'filename.pdf',
              type: 'application/pdf')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(files: [])
  end

  def search(attachments)
    @filtered_attachments = attachments
    if params['created_from'].present?
      @filtered_attachments = @filtered_attachments.where('created_at > ?', params['created_from'].to_datetime)
    end

    if params['created_to'].present?
      @filtered_attachments = @filtered_attachments.where('created_at < ?', params['created_to'].to_datetime)
    end

    @filtered_attachments
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.haml
%p.notice= notice
%p Signed as #{Current.user.email}
%h2 Login and verification

= link_to 'Change password', edit_password_path, class: 'btn btn-primary'
= link_to edit_identity_email_path, class: 'btn btn-primary' do
  Change email address
%br/
= link_to users_path, class: 'btn btn-info' do
  Attachments page
= button_to Current.session, method: :delete, class: 'btn btn-warning' do
  Log out

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentsUpb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_attachment.html.haml
- if file.image?
  = image_tag(file, class: 'document-image')
- elsif file.video?
  = video_tag(url_for(file), class: 'document-video', controls: '')
- elsif file.audio?
  = audio_tag(url_for(file), class: 'document-audio', controls: '')
- else
  = file.filename

app/views/users/_search.html.haml
= form_tag users_path, method: :get do
  %table
    %tr
      %td Date from
      %td= datetime_field_tag 'created_from', params[:start_date]
    %tr
      %td Date to
      %td= datetime_field_tag 'created_to', params[:end_date]
  = submit_tag 'Search', class: 'btn btn-info'
  - if params[:commit].present?
    = link_to users_path, class: 'btn btn-info' do
      Cancel filter

app/views/users/edit.html.haml
%h1 Edit files

= form_with(model: @user, local: true) do |f|
  = f.file_field :files, multiple: true
  %br/
  = f.submit 'Save', class: 'btn btn-info'

= link_to 'Back', users_path, class: 'btn btn-info'

app/views/users/index.html.haml
- from = params[:created_from]
- to = params[:created_to]

%h1 Attachments

= link_to 'Home page', root_path, class: 'btn btn-primary'

= render 'search'
= link_to 'Add attachment', edit_user_path(@current_user),
          class: 'btn btn-primary'
= link_to 'Download filtered list pdf',
          download_user_path(@current_user, created_from: from, created_to: to),
          class: 'btn btn-primary'

%table
  %tr
    %th User
    %th Created at
    %th Attachment
    %th Actions

  - @attachments.each do |file|
    %tr
      %td= file.record.email
      %td= file.created_at.strftime('%d/%m/%Y %H:%M')
      %td= render('attachment', file:)
      %td
        = link_to 'Download',
                  rails_blob_path(file, disposition: 'attachment'),
                  class: 'btn btn-warning'

        = link_to 'Delete',
                  remove_attachment_user_path(file),
                  data: { turbo_method: :delete },
                  class: 'btn btn-danger'